/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayerProgress = IDL.Record({
  'totalMoney' : IDL.Nat,
  'weaponIds' : IDL.Vec(IDL.Nat),
  'currentCity' : IDL.Nat,
  'health' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getLeaderboard' : IDL.Func([], [IDL.Vec(PlayerProgress)], ['query']),
  'loadGameProgress' : IDL.Func([], [PlayerProgress], ['query']),
  'saveGameProgress' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Vec(IDL.Nat), IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayerProgress = IDL.Record({
    'totalMoney' : IDL.Nat,
    'weaponIds' : IDL.Vec(IDL.Nat),
    'currentCity' : IDL.Nat,
    'health' : IDL.Nat,
  });
  
  return IDL.Service({
    'getLeaderboard' : IDL.Func([], [IDL.Vec(PlayerProgress)], ['query']),
    'loadGameProgress' : IDL.Func([], [PlayerProgress], ['query']),
    'saveGameProgress' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Vec(IDL.Nat), IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };